[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
HUGO_VERSION = "v0.88.1"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://miss-reina-t.netlify.app"
HUGO_ENV = "production"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"